/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sales_system;

/**
 *
 * @author USER
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        table_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btn_top_selling = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Sales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        btn_top_selling.setText("Product Profit Report");
        btn_top_selling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_top_sellingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_top_selling, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 650, 280));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_top_sellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_top_sellingActionPerformed
        // TODO add your handling code here:
       // 1. Get the selected row index
    // 1. Get the selected row from your Sales JTable
    int selectedRow = jTable1.getSelectedRow();
    
    // 2. Check if a row is actually selected
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a sale from the table first!");
        return;
    }

    try {
        // 3. Get the Sale ID from the first column (index 0)
        // We convert it to String first, then Parse to Integer to avoid ClassCast errors
        String idString = jTable1.getValueAt(selectedRow, 0).toString();
        Integer saleID = Integer.parseInt(idString); 

        // 4. Database Connection
        java.sql.Connection con = sales_system.db.mycon();
        
        // 5. Create the Parameter Map
        java.util.HashMap<String, Object> para = new java.util.HashMap<>();
        para.put("para_sale_id", saleID); // This name MUST match your Jasper Parameter exactly

        // 6. Path to your report
        String reportPath = "src\\reports\\Profitability_Report.jrxml"; 
        
        // 7. Compile, Fill, and View
        net.sf.jasperreports.engine.JasperReport jr = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportPath);
        net.sf.jasperreports.engine.JasperPrint jp = net.sf.jasperreports.engine.JasperFillManager.fillReport(jr, para, con);
        net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Sale ID format!");
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage());
    }
       
    }//GEN-LAST:event_btn_top_sellingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }
    
    public void table_load() {
    try {
        java.sql.ResultSet rs = sales_system.db.mycon().createStatement().executeQuery("SELECT * FROM sales");
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);

        while (rs.next()) {
            java.util.Vector v = new java.util.Vector();
            v.add(rs.getString("sale_id"));
            v.add(rs.getString("total_bill"));
            v.add(rs.getString("pay_amount"));
            v.add(rs.getString("balance"));
            dt.addRow(v);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    // Finalized UI Design 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_top_selling;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
