/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sales_system;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
/**
 *
 * @author USER
 */
public class Shopping_Cart extends javax.swing.JFrame {

    /**
     * Creates new form Shopping_Cart
     */
    public Shopping_Cart() {
        initComponents();
        load_products();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        com_product = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_grand_total = new javax.swing.JLabel();
        txt_pay = new javax.swing.JTextField();
        lbl_balance = new javax.swing.JLabel();
        Remove = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Shopping Cart");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        getContentPane().add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, -1));

        com_product.setToolTipText("Product Id");
        com_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_productActionPerformed(evt);
            }
        });
        getContentPane().add(com_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 90, -1));

        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Product Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 610, 250));

        lbl_grand_total.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbl_grand_total.setForeground(new java.awt.Color(0, 0, 0));
        lbl_grand_total.setText("Total");
        getContentPane().add(lbl_grand_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 470, 50, -1));

        txt_pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_payKeyReleased(evt);
            }
        });
        getContentPane().add(txt_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 70, -1));

        lbl_balance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbl_balance.setForeground(new java.awt.Color(0, 0, 0));
        lbl_balance.setText("Balance");
        getContentPane().add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Check if the user actually chose a valid ID
    if (com_product.getSelectedItem().toString().equals("Select ID")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid Product ID!");
        return;
    }
    // 1. Get user input
    String id = com_product.getSelectedItem().toString();
    String qtyInput = txt_qty.getText();

    // Validation: Don't allow empty quantity
    if (qtyInput.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter quantity first!");
        return;
    }

    try {
        // 2. Database Lookup: Get Name and Price based on the ID
        java.sql.Connection con = sales_system.db.mycon();
        String sql = "SELECT product_name, sell_price FROM products WHERE product_id = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, id);
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // 3. Extract data from DB result
            String name = rs.getString("product_name");
            double price = rs.getDouble("sell_price");
            double qty = Double.parseDouble(qtyInput);
            double total = price * qty;

            // 4. Add data to the JTable
            javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            java.util.Vector v = new java.util.Vector();
            v.add(id);      // Column 0
            v.add(name);    // Column 1
            v.add(qty);     // Column 2
            v.add(price);   // Column 3
            v.add(total);   // Column 4
            
            dt.addRow(v);
            
            // 5. Update the Grand Total and clear qty field
            calculate_grand_total();
            txt_qty.setText(""); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Product ID not found in database.");
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        com_product.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    int rw = jTable1.getSelectedRow();
    if (rw != -1) { // -1 means no row is selected
        dt.removeRow(rw);
        calculate_grand_total(); // Recalculate after removing
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to remove!");
    }
    }//GEN-LAST:event_RemoveActionPerformed

    private void com_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_productActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_com_productActionPerformed

    private void txt_payKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_payKeyReleased
        // TODO add your handling code here:
        try {
        double total = Double.parseDouble(lbl_grand_total.getText());
        double pay = Double.parseDouble(txt_pay.getText());
        double balance = pay - total;
        
        // Set balance to label
        lbl_balance.setText(String.valueOf(balance));
        
        // Change color to red if pay is not enough
        if (balance < 0) {
            lbl_balance.setForeground(java.awt.Color.RED);
        } else {
            lbl_balance.setForeground(java.awt.Color.BLACK);
        }
    } catch (Exception e) {
        lbl_balance.setText("0.00");
    }
    }//GEN-LAST:event_txt_payKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // 1. Immediate UI Lock to prevent double/triple clicking
    jButton3.setEnabled(false); 

    try {
        java.sql.Connection con = sales_system.db.mycon(); 
        
        // 2. Data Validation
        if (jTable1.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please add items to the cart first!");
            jButton3.setEnabled(true);
            return;
        }

        // 3. Save the main Sales record
        String sql = "INSERT INTO sales (total_bill, pay_amount, balance) VALUES (?,?,?)";
        String sql_update_stock = "UPDATE products SET qty = qty - ? WHERE product_id = ?"; // The Stock Update SQL
        java.sql.PreparedStatement pst = con.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
        
        // Use default values if fields are empty to prevent crashes
        pst.setString(1, lbl_grand_total.getText().isEmpty() ? "0" : lbl_grand_total.getText());
        pst.setString(2, txt_pay.getText().isEmpty() ? "0" : txt_pay.getText());
        pst.setString(3, lbl_balance.getText().isEmpty() ? "0" : lbl_balance.getText());
        pst.executeUpdate();
        
        java.sql.ResultSet rs = pst.getGeneratedKeys();
        int sales_id = 0;
        if (rs.next()) { 
            sales_id = rs.getInt(1); 
        }

        // 4. Save Table Items (The "Details" Loop)
        String sql_details = "INSERT INTO sales_details (sale_id, product_id, product_name, qty, price, total_price) VALUES (?,?,?,?,?,?)";
        java.sql.PreparedStatement pst_details = con.prepareStatement(sql_details);

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Object pid = jTable1.getValueAt(i, 0);
            if (pid != null && !pid.toString().trim().isEmpty()) {
                pst_details.setInt(1, sales_id);
                pst_details.setString(2, jTable1.getValueAt(i, 0).toString());
                pst_details.setString(3, jTable1.getValueAt(i, 1).toString());
                pst_details.setString(4, jTable1.getValueAt(i, 2).toString());
                pst_details.setString(5, jTable1.getValueAt(i, 3).toString());
                pst_details.setString(6, jTable1.getValueAt(i, 4).toString());
                pst_details.executeUpdate(); 
            }
        }

        // --- JASPER REPORT LOGIC ---
        java.io.InputStream reportStream = getClass().getResourceAsStream("/reports/bill.jasper");
        
        if (reportStream != null) {
            java.util.HashMap<String, Object> para = new java.util.HashMap<>();
            para.put("inv_id", sales_id); 
            
            net.sf.jasperreports.engine.JasperPrint jp = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportStream, para, con);
            
            if (jp.getPages().size() > 0) {
                net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);
            }
        }

        // 5. Success and Reset UI
        javax.swing.JOptionPane.showMessageDialog(this, "Sale Completed! ID: " + sales_id);
        
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        lbl_grand_total.setText("0.00");
        txt_pay.setText("");
        lbl_balance.setText("0.00");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // 6. Re-enable button after processing is complete
        jButton3.setEnabled(true);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void calculate_grand_total() {
    double grandTotal = 0;
    int rowCount = jTable1.getRowCount();

    for (int i = 0; i < rowCount; i++) {
        // Look at the "Total" column (Column index 4)
        Object value = jTable1.getValueAt(i, 4);
        
        // Only calculate if the cell is NOT null
        if (value != null) {
            grandTotal += Double.parseDouble(value.toString());
        }
    }
    // Update your Label (make sure the name matches your JLabel)
    lbl_grand_total.setText(String.valueOf(grandTotal));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopping_Cart().setVisible(true);
            }
        });
    }

    private void load_products() {
    try {
        java.sql.Connection con = sales_system.db.mycon();
        java.sql.PreparedStatement pst = con.prepareStatement("SELECT product_id FROM products");
        java.sql.ResultSet rs = pst.executeQuery();
        
        com_product.removeAllItems();
        
        // 1. Add the placeholder first
        com_product.addItem("Select ID"); 
        
        while(rs.next()) {
            com_product.addItem(rs.getString("product_id"));
        }
        
        // 2. Ensure "Select ID" is the one showing when page opens
        com_product.setSelectedIndex(0); 
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remove;
    private javax.swing.JComboBox<String> com_product;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_grand_total;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables
}
