/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sales_system;

/**
 *
 * @author USER
 */


public class Supply extends javax.swing.JFrame {
    String id_to_update = "";
String selected_sid = ""; // This will store the ID of the row you clicked
    /**
     * Creates new form Supply
     */
    public Supply() {
        initComponents();
        supplier_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sup_name = new javax.swing.JTextField();
        txt_sup_tp = new javax.swing.JTextField();
        txt_sup_addr = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Supply Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 200, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        jButton3.setText("Delete");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier Id", "Supplier Name", "Telephone No", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 270));

        jLabel2.setText("Supplier Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setText("Telephone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(txt_sup_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, -1));
        getContentPane().add(txt_sup_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, -1));
        getContentPane().add(txt_sup_addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 80, -1));

        jButton4.setText("Dashboard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Get data from Text Fields
    String name = txt_sup_name.getText();
    String tp = txt_sup_tp.getText();
    String addr = txt_sup_addr.getText();

    // Simple Validation
    if (name.isEmpty() || tp.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in Name and Phone Number!");
        return;
    }

    try {
        // Get Connection and Prepare Statement
        java.sql.Connection con = sales_system.db.mycon();
        java.sql.PreparedStatement pst = con.prepareStatement(
            "INSERT INTO supplier (supplier_name, tp_number, address) VALUES (?,?,?)"
        );

        // Set parameters (prevents SQL injection)
        pst.setString(1, name);
        pst.setString(2, tp);
        pst.setString(3, addr);

        // Execute and Update
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Supplier Added Successfully!");

        // Refresh your JTable and Clear Fields
        supplier_load(); 
        clearFields(); 

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
     int r = jTable1.getSelectedRow();
    
    // Save the ID to our hidden variable (Column 0)
    id_to_update = jTable1.getValueAt(r, 0).toString();
    
    // Send the rest of the data to your visible text fields
    txt_sup_name.setText(jTable1.getValueAt(r, 1).toString());
    txt_sup_tp.setText(jTable1.getValueAt(r, 2).toString());
    txt_sup_addr.setText(jTable1.getValueAt(r, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // Validation: Make sure the hidden ID isn't empty
    if (id_to_update.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a supplier from the table first!");
        return;
    }

    // Get the NEW values from your text fields
    String name = txt_sup_name.getText();
    String tp = txt_sup_tp.getText();
    String addr = txt_sup_addr.getText();

    try {
        java.sql.Connection con = sales_system.db.mycon();
        
        // Prepare the Update Statement
        String sql = "UPDATE supplier SET supplier_name=?, tp_number=?, address=? WHERE sid=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setString(1, name);
        pst.setString(2, tp);
        pst.setString(3, addr);
        pst.setString(4, id_to_update); // Using the hidden ID from the MouseClick

        // Execute
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Supplier Updated Successfully!");

        // Clean up
        supplier_load(); // Refresh JTable
        clearFields();  // Method to empty your text boxes
        id_to_update = ""; // Reset the hidden ID

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Dashboard dsb = new Dashboard();
        dsb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supply().setVisible(true);
            }
        });
    }

    public void supplier_load() {
    try {
        // Get database connection
        java.sql.Connection con = sales_system.db.mycon();
        
        // Execute Query
        java.sql.ResultSet rs = con.createStatement().executeQuery("SELECT * FROM supplier");
        
        // Get the Table Model from your JTable (rename jTable1 if needed)
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0); // Clear existing data

        while (rs.next()) {
            java.util.Vector v = new java.util.Vector();
            
            v.add(rs.getString("sid"));           // ID
            v.add(rs.getString("supplier_name")); // Name
            v.add(rs.getString("tp_number"));     // Phone
            v.add(rs.getString("address"));       // Address
            
            dt.addRow(v);
        }
    } catch (Exception e) {
        System.out.println(e);
        javax.swing.JOptionPane.showMessageDialog(null, "Error loading suppliers: " + e.getMessage());
    }
}
    
    private void clearFields() {
    txt_sup_name.setText("");
    txt_sup_tp.setText("");
    txt_sup_addr.setText("");
    txt_sup_name.requestFocus(); // Put cursor back in name field
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_sup_addr;
    private javax.swing.JTextField txt_sup_name;
    private javax.swing.JTextField txt_sup_tp;
    // End of variables declaration//GEN-END:variables
}
